version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go build -v ./...
  test:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go test -v ./...
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
