version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: on
    steps:
      - checkout
      - run: go test -v ./...
