// Code generated by mockery v1.0.0. DO NOT EDIT.

// DO NOT EDIT MANUALLY. If you make changes to anything in interfaces.go, run make generate-mocks.

package mocks

import gdt "github.com/jaypipes/gdt"
import mock "github.com/stretchr/testify/mock"

// Appendable is an autogenerated mock type for the Appendable type
type Appendable struct {
	mock.Mock
}

// Append provides a mock function with given fields: _a0
func (_m *Appendable) Append(_a0 gdt.Runnable) {
	_m.Called(_a0)
}
