// Code generated by mockery v1.0.0. DO NOT EDIT.

// DO NOT EDIT MANUALLY. If you make changes to anything in interfaces.go, run make generate-mocks.

package mocks

import gdt "github.com/jaypipes/gdt"
import mock "github.com/stretchr/testify/mock"

// ContextAppendable is an autogenerated mock type for the ContextAppendable type
type ContextAppendable struct {
	mock.Mock
}

// Append provides a mock function with given fields: _a0
func (_m *ContextAppendable) Append(_a0 gdt.Runnable) {
	_m.Called(_a0)
}

// Context provides a mock function with given fields:
func (_m *ContextAppendable) Context() *gdt.Context {
	ret := _m.Called()

	var r0 *gdt.Context
	if rf, ok := ret.Get(0).(func() *gdt.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gdt.Context)
		}
	}

	return r0
}
