// Code generated by mockery v1.0.0. DO NOT EDIT.

// DO NOT EDIT MANUALLY. If you make changes to anything in interfaces.go, run make generate-mocks.

package mocks

import mock "github.com/stretchr/testify/mock"
import testing "testing"

// Runnable is an autogenerated mock type for the Runnable type
type Runnable struct {
	mock.Mock
}

// Run provides a mock function with given fields: _a0
func (_m *Runnable) Run(_a0 *testing.T) {
	_m.Called(_a0)
}
